#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------

from hixl.hixl import (
    SUCCESS,
    PARAM_INVALID,
    TIMEOUT,
    NOT_CONNECTED,
    ALREADY_CONNECTED,
    NOTIFY_FAILED,
    UNSUPPORTED,
    FAILED,
    RESOURCE_EXHAUSTED,
    OPTION_ENABLE_USE_FABRIC_MEM,
    OPTION_RDMA_TRAFFIC_CLASS,
    OPTION_RDMA_SERVICE_LEVEL,
    OPTION_BUFFER_POOL,
    OPTION_GLOBAL_RESOURCE_CONFIG,
    OPTION_AUTO_CONNECT,
    OPTION_LOCAL_COMM_RES,
    FEATURE_SUPPORTED,
    FEATURE_NOT_SUPPORTED,
    MemType,
    MEM_DEVICE,
    MEM_HOST,
    TransferOp,
    READ,
    WRITE,
    TransferStatus,
    AsyncConnectStatus,
    NOT_CONNECT,
    CONNECT_PENDING,
    CONNECTING,
    CONNECTED,
    CONNECT_FAILED,
    DISCONNECT_PENDING,
    DISCONNECTING,
    FeatureType,
    AUTO_CONNECT,
    CLIENT_SERVER_COMM,
    MemDesc,
    TransferOpDesc,
    TransferArgs,
    GetTransferStatusArgs,
    TransferResult,
    NotifyDesc,
    Hixl,
    get_capability,
)

__all__ = [
    "SUCCESS",
    "PARAM_INVALID",
    "TIMEOUT",
    "NOT_CONNECTED",
    "ALREADY_CONNECTED",
    "NOTIFY_FAILED",
    "UNSUPPORTED",
    "FAILED",
    "RESOURCE_EXHAUSTED",
    "OPTION_ENABLE_USE_FABRIC_MEM",
    "OPTION_RDMA_TRAFFIC_CLASS",
    "OPTION_RDMA_SERVICE_LEVEL",
    "OPTION_BUFFER_POOL",
    "OPTION_GLOBAL_RESOURCE_CONFIG",
    "OPTION_AUTO_CONNECT",
    "OPTION_LOCAL_COMM_RES",
    "FEATURE_SUPPORTED",
    "FEATURE_NOT_SUPPORTED",
    "MemType",
    "MEM_DEVICE",
    "MEM_HOST",
    "TransferOp",
    "READ",
    "WRITE",
    "TransferStatus",
    "AsyncConnectStatus",
    "NOT_CONNECT",
    "CONNECT_PENDING",
    "CONNECTING",
    "CONNECTED",
    "CONNECT_FAILED",
    "DISCONNECT_PENDING",
    "DISCONNECTING",
    "FeatureType",
    "AUTO_CONNECT",
    "CLIENT_SERVER_COMM",
    "MemDesc",
    "TransferOpDesc",
    "TransferArgs",
    "GetTransferStatusArgs",
    "TransferResult",
    "NotifyDesc",
    "Hixl",
    "get_capability",
]
